Feature/user list
chingu-voyage4/Bears-Team-25 pull request #57
Opened 2018-03-11 10:12 UTC by keith1111

address :    /users  - show all users   (UserList.js)
/users/<user_id>    - show full info of user with that <id>     (UserPage.js)

Maybe we should add field 'login' to database?
in that case link to user page will be like: /users/myLogin    
and now it is like  /users/wefhwufh238yr8923yrghfigriweg
i can not prefer field 'name' for these purposes because names can be duplicate (John Smith, Xing Lee, Maria Fernandez)

2018-03-11 10:46 UTC, nikrb commented
the user is available in the backend as req.user, after login. We're planning to use github for main login so unique name won't be an issue, for now atleast. so route `/user/:id*?` will return detail of specified user id, or logged in user if param is not specified. Always open to discussion, but that's my initial take

2018-03-11 10:59 UTC, nikrb commented
Looks great, but before we merge I'd like to hear @giovannisampaio and @jenovs comments on the following:
1. I think clicking on the users menu should show all users.
2. We need another menu item 'profile' to show my profile.
3. Why open a new tab when we click on a user to see that user's profile?

2018-03-11 11:03 UTC, keith1111 commented
OK lets listen and i will rewrite if we decide to change something

2018-03-11 12:16 UTC, jenovs commented on frontend/src/App.js
> +
Unnecessary line

2018-03-11 12:19 UTC, jenovs commented on frontend/src/UserList/UserList.js
> +                  <a target="_blank" href={`/users/${d._id}`}>
Use `Link` and `Route` from `react-router-dom` to create navigation inside the same page.

2018-03-11 12:21 UTC, jenovs requested changes
Replace opening of new page with router navigation.

2018-03-11 12:32 UTC, jenovs commented
Regarding @nikrb comment:
1. I suppose it should be admin only feature, so, yes `Users` should show list of all users.
3. The whole idea behind single page app is that everything happens on a... single page :grinning: 

Apart from that it's fine.

P.S. I personally don't like creating tables manually (I did it for `Articles` component), so for `Assets` I used external component. I recommend to look into it.

2018-03-12 11:15 UTC, keith1111 commented
Replaced tag a with link
Rewrote href of links to lead them to wished addresses
Added some exception to eslint config (to remove odd errors)

2018-03-12 12:45 UTC, nikrb commented on frontend/src/UserList/UserPage.js
> +	    {userInfo}
code indents look wrong here but look ok in local editor, weird

2018-03-12 12:51 UTC, nikrb commented on .eslintrc.json
> +    "jsx-a11y/anchor-is-valid": [ "error", {
not sure about this. @jenovs can you have a look at this please. linter is complaining <Link> requires an href attribute which doesn't make sense to me.

2018-03-12 16:29 UTC, nikrb commented
sorry keith we have three failing tests- `npm test` in frontend directory. Shout it you need a hand.
1. src/Navbar/Navbar.test.js
2. src/AssetEdit/utils.test.js
3. src/LandingPage/LandingPage.test.js

@jenovs the second one, do you see the same?:
```
    /home/nik/projects/voyage4/bears-25/frontend/src/AssetEdit/utils.test.js:10
      it('readFile should convert file to dataURL', async () => {
```
That doesn't look right, it's complaining about async. Am I doing something wrong?

2018-03-12 16:43 UTC, nikrb commented
@keith1111 Point number 3 is a generated css class change. Landing page still looks good to me so easy to fix, just update the snapshot, `npm test -- -u`.

2018-03-12 16:47 UTC, jenovs commented
1. A link was added to `Navbar` so test should be changed to expect `7`
3. Landing page is missing `import 'jest-styled-components';`

2018-03-12 16:50 UTC, nikrb commented
I have added `jest-styled-components` to issues #58

2018-03-14 07:51 UTC, jenovs commented on .eslintrc.json
> +
Unnecessary whitespace

2018-03-14 09:41 UTC, keith1111 commented
removed whitespace

2018-03-16 00:00 UTC, nikrb commented
@keith1111 `jest-styled-components` output looks good, but you need to update the snapshots in order for the tests to pass :)

Also I still see linter errors:
```
/home/nik/projects/voyage4/bears-25/frontend/src/LandingPage/LandingPage.test.js
  4:8  error  Absolute imports should come before relative imports  import/first

/home/nik/projects/voyage4/bears-25/frontend/src/UserList/UserList.js
  3:1  error  Expected empty line after import statement not followed by another import  import/newline-after-import

/home/nik/projects/voyage4/bears-25/frontend/src/UserList/UserPage.js
  4:1  error  Expected empty line after import statement not followed by another import  import/newline-after-import
```

2018-03-16 08:07 UTC, jenovs approved these changes

2018-03-18 11:47 UTC, jenovs approved these changes

2018-03-18 21:28 UTC, giovannisampaio approved these changes

2018-03-18 22:54 UTC, merged