Feature/sidebar
chingu-voyage4/Bears-Team-25 pull request #59
Opened 2018-03-13 23:14 UTC by giovannisampaio

CMSContainer wraps Sidebar and ContantArea. It uses styled components with flexbox to organize the layout.

2018-03-14 08:01 UTC, jenovs requested changes
1. Invalid DOM (look into console).
2. Linting errors.

2018-03-14 10:39 UTC, keith1111 commented
Console error - Seems Collapsible.js line 15 does not need <a></a>  around {children}
Kool look , btw.

2018-03-15 23:51 UTC, nikrb commented
looks good to me.
@jenovs are you happy with changes you requested?

2018-03-16 08:06 UTC, jenovs approved these changes

2018-03-16 16:29 UTC, merged